#title, author and description are mandatory fields
title = "Raiden Hypercarry"
author = "loghost#2690"
description = "Raiden with Kazuha/Sara/Bennett"
# version is an optional field for authors to keep track
version = "0.1.0"
# characters should be array of character names (all lowercase); this is mandatory
characters = ["raidenshogun", "kujousara", "bennett", "kaedeharakazuha"]
# config is the action list, stored in multiline string
config = '''
##Default Enemy
target lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;
#target lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

##Actions List
active raidenshogun;

energy every interval=200,300 amount=1;

raidenshogun skill  +if=.status.raidenskill<360;

raidenshogun skill  +if=.cd.raidenshogun.burst<600&&.status.btburst==0;

bennett burst  +if=.cd.kujousara.burst<270;

kaedeharakazuha burst  +if=.status.btburst>0;

kujousara skill,aim  +if=.status.btburst>0&&.cd.kujousara.burst<300;
kujousara burst[wave_attack_procs=111]  +if=.status.btburst>0;

raidenshogun burst; 
raidenshogun attack,attack,attack,charge,attack,attack,attack,charge,attack,attack,charge,attack,charge  +if=.status.raidenburst>0;

bennett skill  +if=.status.btburst==0;
kaedeharakazuha skill,high_plunge; 
kujousara skill,aim; 
'''
