title = "Tartaglia Reverse Vape Sucrose (Pyro VV)"
author = "Tsym#2586"
recommended_rotation_length = "24.0"
recommended_enemy_count = 0
description = '''Recommended Rotation Duration: 24.0
Expected Rotation: Bennett Q E -> Sucrose E E (Rotation 1, only 1 E for Rotation 2) -> Xiangling Q E -> Tartaglia rQ + E + (N3C) x 4 -> Bennett E -> Xiangling -> Tartaglia CA -> Bennett E -> Xiangling -> Tartaglia (CA) x2'''
characters = ['sucrose', 'xiangling', 'bennett', 'tartaglia']
version = "0.1"
kqm_standard_character_configs = '''

##Character Definitions
xiangling char lvl=90/90 cons=4 talent=9,9,9;
xiangling add weapon="the catch" lvl=90/90 refine=5;
xiangling add set="seal of insulation" count=4;
xiangling add stats hp=4780 atk=311 atk%=0.466 pyro%=0.466 cr=0.311;
xiangling add stats atk%=.0992 cr=.2317 cd=.8606 em=39.64 er=.3306 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

bennett char lvl=80/90 cons=4 talent=6,9,9;
bennett add weapon="blackcliff longsword" lvl=90/90 refine=3;
bennett add set="noblesse oblige" count=4;
bennett add stats hp=4780 atk=311 er=.518 pyro%=0.466 cr=0.311;
bennett add stats atk%=.0992 cr=.0662 cd=.1324 em=39.64 er=.3857 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

sucrose char lvl=90/90 cons=4 talent=6,6,6;
sucrose add weapon="thrilling tales of dragon slayers" lvl=90/90 refine=5;
sucrose add set="viridescent venerer" count=4;
sucrose add stats hp=4780 atk=311 em=561;
sucrose add stats atk%=.0992 cr=.0662 cd=.1324 em=138.74 er=.1102 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

tartaglia char lvl=80/90 cons=0 talent=6,9,9;
tartaglia add weapon="the viridescent hunt" lvl=90/90 refine=3;
tartaglia add set="heart of depth" count=4;
tartaglia add stats hp=4780 atk=311 atk%=0.466 hydro%=0.466 cd=0.622;
tartaglia add stats atk%=.0992 cr=.3641 cd=.4634 em=39.64 er=.3306 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

'''

config = '''##Default Enemy
target lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;
# target lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

##HP Particles
energy every interval=480,720 amount=1;

##Actions List
active tartaglia;

tartaglia attack:3,charge,
          attack:3,charge,
          attack:3,charge,
          attack:3,charge
          +if=.status.tartagliamelee>0
          && .status.btburst>0
          && .status.xianglingburst>0;

bennett burst,skill
        +if=.energy.xiangling>69;

sucrose skill
        +if=.debuff.res.t1.vvpyro==0
        && .element.t1.pyro==1
        && .status.btburst>0;
sucrose attack
        +if=.debuff.res.t1.vvpyro==0
        && .element.t1.pyro==1
        && .status.btburst>0;

xiangling burst,skill
          +if=.status.btburst>0
          +swap_to=tartaglia;

tartaglia burst;
tartaglia skill
          +if=.status.btburst>0
          && .status.xianglingburst>0;

# Funnelling
bennett skill
        +if=.energy.xiangling<70
        +swap_to=xiangling;
'''
