title = "Tartaglia Reverse Vape Sucrose (Pyro VV)"
author = "Tsym#2586"
recommended_rotation_length = "24.0"
recommended_minimum_er = { xiangling = 1.9896, sucrose = 1.1102, tartaglia = 1.3306, bennett = 2.1707 }
recommended_loadouts = { xiangling = 'the catch, 4 seal of insulation', sucrose = 'thrilling tales of dragon slayers, 4 viridescent venerer', tartaglia = 'the viridescent hunt, 4 heart of depth', bennett = 'blackcliff longsword, 4 noblesse oblige' }
recommended_enemy_count = 2
description = '''Recommended Rotation Duration: 24.0
Recommended Minimum ER by Character: xiangling: 199%; sucrose: 111%; tartaglia: 133%; bennett: 217%
Rotation Built for the Following Weapon/Artifacts: xiangling: the catch, 4 seal of insulation; sucrose: thrilling tales of dragon slayers, 4 viridescent venerer; tartaglia: the viridescent hunt, 4 heart of depth; bennett: blackcliff longsword, 4 noblesse oblige
Recommended Enemy Count: 2
Rotation: Bennett Q E -> Sucrose E E (Rotation 1, only 1 E for Rotation 2) -> Xiangling Q E -> Tartaglia rQ + E + (N3C) x 4 -> Bennett E -> Xiangling -> Tartaglia CA -> Bennett E -> Xiangling -> Tartaglia (CA) x2'''
characters = ['xiangling', 'sucrose', 'tartaglia', 'bennett']

kqm_standard_character_configs = '''

##Character Definitions
char+=xiangling ele=pyro lvl=90 hp=10874.915 atk=225.141 def=668.871 em=96.000 cr=.05 cd=0.5 cons=4 talent=9,9,9;
weapon+=xiangling label="the catch" atk=510 er=0.459 refine=5;
art+=xiangling label="seal of insulation" count=4;
stats+=xiangling label=main hp=4780 atk=311 atk%=0.466 pyro%=0.466 cr=0.311;
stats+=xiangling label=subs atk%=.0992 cr=.2317 cd=.8606 em=39.64 er=.3306 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

char+=bennett ele=pyro lvl=80 hp=1 atk=178 def=1 er=0.267 cr=.05 cd=0.5 cons=4 talent=6,9,9;
weapon+=bennett label="blackcliff longsword" atk=564.784 cd=0.368 refine=3;
art+=bennett label="noblesse oblige" count=4;
stats+=bennett label=main hp=4780 atk=311 er=.518 pyro%=0.466 cr=0.311;
stats+=bennett label=subs atk%=.0992 cr=.0662 cd=.1324 em=39.64 er=.3857 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

char+=sucrose ele=anemo lvl=90 hp=9243.678 atk=169.918 def=702.997 anemo%=0.240 cr=.05 cd=0.5 cons=4 talent=6,6,6;
weapon+=sucrose label="thrilling tales of dragon slayers" atk=401.294 hp%=0.352 refine=5;
art+=sucrose label="viridescent venerer" count=4;
stats+=sucrose label=main hp=4780 atk=311 em=561;
stats+=sucrose label=subs atk%=.0992 cr=.0662 cd=.1324 em=138.74 er=.1102 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

char+=tartaglia ele=hydro lvl=80 hp=1 atk=280 def=1 hydro%=0.288 cr=0.05 cd=0.5 cons=0 talent=6,9,9;
weapon+=tartaglia label="the viridescent hunt" atk=510 cr=0.276 refine=3;
art+=tartaglia label="heart of depth" count=4;
stats+=tartaglia label=main hp=4780 atk=311 atk%=0.466 hydro%=0.466 cd=0.622;
stats+=tartaglia label=subs atk%=.0992 cr=.3641 cd=.4634 em=39.64 er=.3306 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

'''

config = '''##Default Enemy
target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;
target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

##Actions List
active+=tartaglia;

# HP particle simulation. Per srl:
# it adds 1 particle randomly, uniformly distributed between 200 to 300 frames after the last time an energy drops
# so in the case above, it adds on avg one particle every 250 frames in effect
# so over 90s of combat that's 90 * 60 / 250 = 21.6 on avg
# From elijam assumptions: https://discord.com/channels/763583452762734592/851428030094114847/884832120650993805
energy+=every interval=200,300 amount=1;

actions+=sequence_strict target=tartaglia exec=attack,attack,attack,charge,attack,attack,attack,charge,attack,attack,attack,charge,attack,attack,attack,charge if=.status.tartagliamelee>0&&.status.btburst>0&&.status.xianglingburst>0;

actions+=sequence_strict target=bennett exec=burst,skill if=.energy.xiangling>69;
actions+=sequence_strict target=sucrose exec=skill if=.debuff.res.vvpyro==0&&.element.pyro==1&&.status.btburst>0;
actions+=sequence_strict target=sucrose exec=skill if=.status.btburst>0;
actions+=sequence_strict target=sucrose exec=attack if=.debuff.res.vvpyro==0&&.element.pyro==1&&.status.btburst>0;
actions+=sequence_strict target=xiangling exec=burst,skill if=.status.btburst>0&&.debuff.res.vvpyro==1 swap=tartaglia;

actions+=sequence_strict target=tartaglia exec=burst;
actions+=sequence_strict target=tartaglia exec=skill if=.status.btburst>0&&.status.xianglingburst>0;

actions+=sequence_strict target=sucrose exec=skill if=.debuff.res.vvhydro==0&&.element.hydro==1&&.status.xianglingburst==0;

# Funnelling
actions+=sequence_strict target=bennett exec=skill if=.energy.xiangling<70 swap=xiangling;

actions+=sequence_strict exec=aim,aim target=tartaglia swap=bennett if=.element.pyro==0;
actions+=aim target=tartaglia swap=bennett;
actions+=attack target=sucrose;
actions+=attack target=xiangling active=xiangling;
actions+=attack target=bennett active=bennett;
'''
