title = "Hu Tao Amber VV"
author = "Tsym#2586"
recommended_rotation_length = "21.0"
recommended_minimum_er = { amber = 2.2432, sucrose = 1.1102, xingqiu = 2.2538, hutao = 1.1102 }
recommended_loadouts = { amber = 'favonius warbow, 4 instructor', sucrose = 'thrilling tales of dragon slayers, 4 viridescent venerer', xingqiu = 'favonius sword, 4 seal of insulation', hutao = 'deathmatch, 4 crimson witch of flames' }
recommended_enemy_count = 1
description = '''Recommended Rotation Duration: 21.0
Recommended Minimum ER by Character: amber: 224%; sucrose: 111%; xingqiu: 225%; hutao: 111%
Rotation Built for the Following Weapon/Artifacts: amber: favonius warbow, 4 instructor; sucrose: thrilling tales of dragon slayers, 4 viridescent venerer; xingqiu: favonius sword, 4 seal of insulation; hutao: deathmatch, 4 crimson witch of flames
Recommended Enemy Count: 1
Rotation: Xingqiu E Q -> Amber Q (Stay onfield for .5s to proc Instructor) -> Sucrose E N1 (Pyro VV) -> Hu Tao E 8N2C + Q (Omitted in rotation 2 as Hu Tao does not generate enough energy) -> Xingqiu. Everything from Hu Tao is getting vaped except for some Normals here and there.'''
characters = ['amber', 'sucrose', 'xingqiu', 'hutao']
version = "0.1.0"

kqm_standard_character_configs = '''

##Character Definitions
char+=hutao ele=pyro lvl=90 hp=15552 atk=106 def=1 cr=0.05 cd=0.884 cons=0 talent=9,9,9 starthp=3000;
weapon+=hutao label="deathmatch" atk=454 cr=.368 refine=3;
art+=hutao label="crimson witch of flames" count=4;
stats+=hutao label=main hp=4780 atk=311 em=187 pyro%=0.466 cd=0.622;
stats+=hutao label=subs atk%=.0992 cr=.3972 cd=.662 em=79.28 er=.1102 hp%=.1984 hp=507.88 atk=33.08 def%=.124 def=39.36;

char+=xingqiu ele=hydro lvl=80 hp=1 atk=188 def=1 atk%=0.240 cr=.05 cd=0.5 cons=4 talent=6,9,9;
weapon+=xingqiu label="favonius sword" atk=454.363 er=0.613 refine=3;
art+=xingqiu label="seal of insulation" count=4;
stats+=xingqiu label=main hp=4780 atk=311 atk%=0.466 hydro%=0.466 cr=0.311;
stats+=xingqiu label=subs atk%=.0992 cr=.2648 cd=.662 em=39.64 er=.4408 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

char+=amber ele=pyro lvl=80 hp=1 atk=208 def=1 atk%=0.24 cr=.05 cd=0.5 cons=0 talent=6,9,9;
weapon+=amber label="favonius warbow" atk=454 er=0.615 refine=3;
art+=amber label="instructor" count=4;
stats+=amber label=main hp=4780 atk=311 er=.518 pyro%=0.466 cr=0.311;
stats+=amber label=subs atk%=.0992 cr=.2 cd=.1324 em=39.64 er=.1102 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

char+=sucrose ele=anemo lvl=90 hp=9243.678 atk=169.918 def=702.997 anemo%=0.240 cr=.05 cd=0.5 cons=4 talent=6,6,6;
weapon+=sucrose label="thrilling tales of dragon slayers" atk=401.294 hp%=0.352 refine=5;
art+=sucrose label="viridescent venerer" count=4;
stats+=sucrose label=main hp=4780 atk=311 em=561;
stats+=sucrose label=subs atk%=.0992 cr=.0662 cd=.1324 em=138.74 er=.1102 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

'''

config = '''##Default Enemy
target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;
# target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

##Actions List
active+=xingqiu;

# HP particle simulation. Per srl:
# it adds 1 particle randomly, uniformly distributed between 200 to 300 frames after the last time an energy drops
# so in the case above, it adds on avg one particle every 250 frames in effect
# so over 90s of combat that's 90 * 60 / 250 = 21.6 on avg
# From elijam assumptions: https://discord.com/channels/763583452762734592/851428030094114847/884832120650993805
energy+=every interval=200,300 amount=1;

# Drops 1 N2C - check ability usage figures to confirm
# actions+=sequence_strict target=hutao exec=jump if=.status.paramita>300&&.status.paramita<350;

actions+=sequence_strict target=hutao exec=burst if=.status.paramita<20&&.status.paramita>0;
actions+=sequence_strict target=hutao exec=attack,attack,charge if=.status.paramita>20&&.status.paramita<=60;
actions+=sequence_strict target=hutao exec=attack,attack,charge,dash if=.status.paramita>60&&.stam.hutao>180;
actions+=sequence_strict target=hutao exec=attack,attack,charge,jump if=.status.paramita>60;

actions+=sequence_strict target=xingqiu exec=skill[orbital=1],burst[orbital=1],attack;
# Need a jump as a waiting mechanism before it's time to get 4 instructor
actions+=sequence_strict target=amber exec=burst,jump if=.status.xqburst>0&&.status.xqburst>720 swap=sucrose;
actions+=sequence_strict target=sucrose exec=skill,attack swap=hutao if=.cd.hutao.skill<120&&.status.xqburst>720;

actions+=sequence_strict target=hutao exec=skill if=.status.xqburst>720;

actions+=attack target=xingqiu;
actions+=attack target=hutao active=hutao;
'''
