title = "Melt Ganyu Xiangling (6 shots)"
author = "Tsym#2586"
recommended_rotation_length = "20.5"
recommended_minimum_er = { xiangling = 2.728, ganyu = 1.1102, bennett = 2.795, zhongli = 1.4162000000000001 }
recommended_loadouts = { xiangling = 'the catch, 4 seal of insulation', ganyu = "hamayumi, 4 wanderer's troupe", bennett = 'festering desire, 4 noblesse oblige', zhongli = 'favonius lance, 4 instructor' }
recommended_enemy_count = 2
description = '''Recommended Rotation Duration: 20.5
Recommended Minimum ER by Character: xiangling: 273%; ganyu: 111%; bennett: 280%; zhongli: 142%
Rotation Built for the Following Weapon/Artifacts: xiangling: the catch, 4 seal of insulation; ganyu: hamayumi, 4 wanderer's troupe; bennett: festering desire, 4 noblesse oblige; zhongli: favonius lance, 4 instructor
Recommended Enemy Count: 2
Rotation: Bennett E -> Zhongli E (away from enemy) -> Bennett Q -> Xiangling Q E -> Ganyu E + 6 CA (all Ganyu shots melted, Bennett buff for 4/6)'''
characters = ['xiangling', 'ganyu', 'bennett', 'zhongli']
version = "0.1.0"

kqm_standard_character_configs = '''

##Character Definitions
xiangling char lvl=80/90 cons=4 talent=6,9,9;
xiangling add weapon="the catch" refine=5 lvl=90/90;
xiangling add set="seal of insulation" count=4;
xiangling add stats hp=4780 atk=311 er=.518 pyro%=0.466 cr=0.311;
xiangling add stats atk%=.0992 cr=.1655 cd=.7282 em=39.64 er=.5510 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

zhongli char lvl=80/90 cons=0 talent=6,9,9;
zhongli add weapon="favonius lance" refine=3 lvl=90/90;
zhongli add set="instructor" count=4;
zhongli add stats hp=4780 atk=311 hp%=1 cr=0.311;
zhongli add stats atk%=.0992 cr=.2648 cd=.1324 em=39.64 er=.1102 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

bennett char lvl=80/90 cons=4 talent=6,9,9;
bennett add weapon="festering desire" refine=5 lvl=90/90;
bennett add set="noblesse oblige" count=4;
bennett add stats hp=4780 atk=311 er=.518 pyro%=0.466 cr=0.311;
bennett add stats atk%=.0992 cr=.0662 cd=.1324 em=39.64 er=.5510 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

ganyu char lvl=90/90 cons=0 talent=9,9,9;
# Note - Prototype crescent is considered better in the guide, but that doesn't consider Bennett buff I don't think
# Hamayumi works better in Bennett buff
ganyu add weapon="hamayumi" refine=3 lvl=90/90;
# ganyu add set="reminiscence of shime" count=4;
ganyu add set="wanderer's troupe" count=4;
ganyu add stats hp=4780 atk=311 em=187 cryo%=0.466 cr=0.311;
ganyu add stats atk%=.1984 cr=.2317 cd=.7282 em=118.92 er=.1102 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

'''

config = '''##Default Enemy
target lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;
target lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

##Actions List
active bennett;

# HP particle simulation. Per srl:
# it adds 1 particle randomly, uniformly distributed between 200 to 300 frames after the last time an energy drops
# so in the case above, it adds on avg one particle every 250 frames in effect
# so over 90s of combat that's 90 * 60 / 250 = 21.6 on avg
energy every interval=200,300 amount=1;

bennett skill +if=.element.pyro==0&&.element.cryo==0;

# Attacks are to create the shield right before swapping
zhongli attack,attack,skill[hold_nostele=1] +if=.energy.xiangling>70&&.cd.bennett.burst<60;

bennett burst,skill +if=.cd.xiangling.skill<120&&.cd.xiangling.burst<120;
bennett burst +if=.cd.xiangling.skill<50&&.cd.xiangling.burst<50;

xiangling burst,skill +if=.status.xianglingguoba==0&&.status.btburst>0;

# Added lock to slow down shots to align with calcs
# Apparently you can only fit 6 CA in. Sim appears to do a lot better than that, so we artificially constrain it to 6 to be realistic
# Also need to lock her in place as well
# ganyu skill,aim,aim,dash,aim,dash,aim,aim,aim +if=.status.xianglingburst>0 +swap_lock=800 +swap_lock=700;
ganyu skill,aim,aim,aim,aim,dash,dash,dash,dash,dash,dash,aim +if=.status.xianglingburst>0 +swap_lock=800 +swap_lock=700;

bennett skill,attack +swap_to=xiangling +if=.energy.xiangling<65;
bennett skill  +if=.energy.xiangling<75;

zhongli attack ;
xiangling attack  +is_onfield;
'''
