title = "National with Kazuha"
author = "Tsym#2586"
recommended_rotation_length = "23.5"
recommended_minimum_er = { xiangling = 1.9896, xingqiu = 2.0334, bennett = 2.1707, kaedeharakazuha = 1.9037 }
recommended_loadouts = { xiangling = 'the catch, 4 seal of insulation', xingqiu = 'favonius sword, 4 seal of insulation', bennett = 'blackcliff longsword, 4 noblesse oblige', kazuha = 'iron sting, 4 viridescent venerer' }
recommended_enemy_count = 1
description = '''Recommended Rotation Duration: 23.5
Recommended Minimum ER by Character: xiangling: 199%; xingqiu: 203%; bennett: 217%; kazuha: 190%
Rotation Built for the Following Weapon/Artifacts: xiangling: the catch, 4 seal of insulation; xingqiu: favonius sword, 4 seal of insulation; bennett: blackcliff longsword, 4 noblesse oblige; kazuha: iron sting, 4 viridescent venerer
Recommended Enemy Count: 1
Rotation: Xingqiu E Q -> Kazuha Q -> Bennett E Q -> Kazuha E (Hold) P (double VV) -> Xiangling Q E -> Xingqiu AA -> Bennett E -> Xiangling -> Bennett E -> Xiangling. Attacks weaved wherever possible to proc Rainswords (13 waves during rotation). ~10/12 Pyronado hits vaped in ST.'''
characters = ['xiangling', 'xingqiu', 'bennett', 'kaedeharakazuha']
version = "0.1.0"

kqm_standard_character_configs = '''

##Character Definitions
xiangling char lvl=90/90 cons=4 talent=9,9,9;
xiangling add weapon="the catch" refine=5 lvl=90/90;
xiangling add set="seal of insulation" count=4;
xiangling add stats hp=4780 atk=311 atk%=.466 pyro%=0.466 cr=0.311;
xiangling add stats atk%=.0992 cr=.2317 cd=.662 em=99.1 er=.3306 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

xingqiu char lvl=80/90 cons=4 talent=6,9,9;
xingqiu add weapon="favonius sword" refine=3 lvl=90/90;
xingqiu add set="seal of insulation" count=4;
xingqiu add stats hp=4780 atk=311 atk%=0.466 hydro%=0.466 cr=0.311;
xingqiu add stats atk%=.0992 cr=.331 cd=.7944 em=39.64 er=.2204 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

bennett char lvl=80/90 cons=4 talent=6,9,9;
bennett add weapon="blackcliff longsword" refine=3 lvl=90/90;
bennett add set="noblesse oblige" count=4;
bennett add stats hp=4780 atk=311 er=.518 pyro%=0.466 cr=0.311;
bennett add stats atk%=.0992 cr=.0662 cd=.1324 em=39.64 er=.3857 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

kaedeharakazuha char lvl=90/90 cons=0 talent=6,6,6;
kaedeharakazuha add weapon="iron sting" refine=3 lvl=90/90;
kaedeharakazuha add set="viridescent venerer" count=4;
kaedeharakazuha add stats hp=4780 atk=311 er=.518 em=374;
kaedeharakazuha add stats atk%=.0992 cr=.0662 cd=.1324 em=138.74 er=.3857 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

'''

config = '''##Default Enemy
target lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;
# target lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

##Actions List
active bennett;

# HP particle simulation. Per srl:
# it adds 1 particle randomly, uniformly distributed between 200 to 300 frames after the last time an energy drops
# so in the case above, it adds on avg one particle every 250 frames in effect
# so over 90s of combat that's 90 * 60 / 250 = 21.6 on avg
# From elijam assumptions: https://discord.com/channels/763583452762734592/851428030094114847/884832120650993805
energy every interval=200,300 amount=1;

xingqiu skill,burst[orbital=1],attack; 
kaedeharakazuha burst  +if=.cd.xingqiu.skill>900&&.energy.xiangling>70;

bennett skill,burst  +if=.cd.xiangling.burst<120&&.cd.xiangling.skill<150&&.energy.xiangling>73;

kaedeharakazuha skill[hold=1],high_plunge  +if=.status.btburst>0&&.debuff.res.vvpyro==0;

xiangling burst,attack,skill  +if=.status.btburst>0;

# Funnelling - only used when XL burst is off as otherwise you steal vapes
bennett attack,skill  +if=.status.xqburst>0&&.status.xianglingburst<360&&.energy.xiangling<73 +swap_to=xiangling;
bennett skill  +if=.status.xianglingburst<240&&.energy.xiangling<73 +swap_to=xiangling;

xingqiu attack  +if=.status.xqburst>0&&.status.btburst>0;
xiangling attack  +is_onfield;
bennett attack  +is_onfield;
xingqiu attack  +is_onfield;
'''
