title = "C6 Noelle with Double Electro"
author = "Tsym#2586"
recommended_rotation_length = "21.0"
recommended_minimum_er = { ningguang = 1.2204, noelle = 1.3306, fischl = 1.2755, beidou = 1.8282 }
recommended_loadouts = { ningguang = 'thrilling tales of dragon slayers, 4 archaic petra', noelle = "serpent spine, 4 gladiator's finale", fischl = "the stringless, 2 thundering fury, 2 gladiator's finale", beidou = 'luxurious sea-lord, 4 seal of insulation' }
recommended_enemy_count = 2
description = '''Recommended Rotation Duration: 21.0
Recommended Minimum ER by Character: ningguang: 122%; noelle: 133%; fischl: 128%; beidou: 183%
Rotation Built for the Following Weapon/Artifacts: ningguang: thrilling tales of dragon slayers, 4 archaic petra; noelle: serpent spine, 4 gladiator's finale; fischl: the stringless, 2 thundering fury, 2 gladiator's finale; beidou: luxurious sea-lord, 4 seal of insulation
Recommended Enemy Count: 2
Rotation: Fischl Q -> Ningguang N2 (trigger AP) -> Beidou E Q N1 -> Ningguang E -> Noelle Q E N4 -> Beidou Q (perfect counter) -> Fischl E -> Ningguang Q E -> Noelle 2N4. Attacks weaved where possible for Beidou procs (~9 during rotation).'''
characters = ['ningguang', 'noelle', 'fischl', 'beidou']
version = "0.1.0"

kqm_standard_character_configs = '''

##Character Definitions
noelle char lvl=90/90 cons=6 talent=9,9,9;
noelle add weapon="serpent spine" refine=3 lvl=90/90;
# noelle add weapon="whiteblind" refine=3 lvl=90/90;
noelle add set="gladiator's finale" count=4;
noelle add stats hp=4780 atk=311 def%=0.518 geo%=0.466 cd=0.622;
noelle add stats atk%=.0992 cr=.3972 cd=.5296 em=39.64 er=.3306 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

ningguang char lvl=80/90 cons=4 talent=6,9,9;
ningguang add weapon="thrilling tales of dragon slayers" refine=5 lvl=90/90;
ningguang add set="archaic petra" count=4;
ningguang add stats hp=4780 atk=311 atk%=0.466 geo%=0.466 cr=0.311;
ningguang add stats atk%=.0992 cr=.1324 cd=.4634 em=39.64 er=.2204 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

fischl char lvl=80/90 cons=4 talent=6,9,9;
fischl add weapon="the stringless" refine=3 lvl=90/90;
fischl add set="thundering fury" count=2;
fischl add set="gladiator's finale" count=2;
fischl add stats hp=4780 atk=311 atk%=0.466 electro%=0.466 cr=0.311;
fischl add stats atk%=.0992 cr=.1986 cd=.662 em=39.64 er=.2755 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

beidou char lvl=80/90 cons=4 talent=6,9,9;
beidou add weapon="luxurious sea-lord" refine=5 lvl=90/90;
# beidou add weapon="serpent spine" refine=3 lvl=90/90;
beidou add set="seal of insulation" count=4;
beidou add stats hp=4780 atk=311 er=.518 electro%=0.466 cr=0.311;
beidou add stats atk%=.1984 cr=.331 cd=.7944 em=39.64 er=.1102 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

'''

config = '''##Default Enemy
target lvl=100 resist=.1;
target lvl=100 resist=.1;

##Actions List
active noelle;

# HP particle simulation. Per srl:
# it adds 1 particle randomly, uniformly distributed between 200 to 300 frames after the last time an energy drops
# so in the case above, it adds on avg one particle every 250 frames in effect
# so over 90s of combat that's 90 * 60 / 250 = 21.6 on avg
# From elijam assumptions: https://discord.com/channels/763583452762734592/851428030094114847/884832120650993805
energy every interval=200,300 amount=1;

fischl burst  +if=.status.noelleq==0;
fischl skill,attack +if=.status.fischloz==0&&.status.beidouburst>0;
fischl skill  +if=.status.fischloz==0;

# Dash to simulate picking up crystal shield for petra
ningguang attack,attack,dash +if=.status.beidouburst==0&&.cd.beidou.burst<120&&.energy.beidou>76 +swap_to=beidou;
beidou skill,burst,attack +if=.energy.noelle>55;
beidou burst,attack +if=.energy.fischl>57;
ningguang attack,skill,attack +if=.status.beidouburst>0&&.status.ningguangskillparticleICD==0 +swap_to=noelle;

ningguang burst +if=.status.beidouburst>0&&.energy.noelle<50&&.status.ningguangskillparticleICD==0&&.status.fischloz>120;
ningguang attack,skill,attack +if=.status.beidouburst>0&&.status.ningguangskillparticleICD==0&&.energy.noelle<50 +swap_to=noelle;
beidou skill[counter=2],attack +if=.energy.beidou<65;

noelle burst,skill,dash; 
noelle attack  +if=.status.noelleq>0;
'''
