title = "Raiden Beidou Bennett Xiangling Desync"
author = "Tsym#2586"
recommended_rotation_length = "nan"
recommended_minimum_er = { xiangling = 1.2204, bennett = 2.1707, raiden = 2.1994000000000002, beidou = 1.3102 }
recommended_loadouts = { xiangling = 'deathmatch, 4 crimson witch of flames', bennett = 'blackcliff longsword, 4 noblesse oblige', raiden = 'the catch, 4 seal of insulation', beidou = 'serpent spine, 4 seal of insulation' }
recommended_enemy_count = 2
description = '''Recommended Rotation Duration: nan
Recommended Minimum ER by Character: xiangling: 122%; bennett: 217%; raiden: 220%; beidou: 131%
Rotation Built for the Following Weapon/Artifacts: xiangling: deathmatch, 4 crimson witch of flames; bennett: blackcliff longsword, 4 noblesse oblige; raiden: the catch, 4 seal of insulation; beidou: serpent spine, 4 seal of insulation
Recommended Enemy Count: 2
Rotation: No fixed rotation and sim is run over 90 seconds. Ordering of ability usage until 20s goes something like:
Raiden E -> Bennett Q E -> Xiangling Q E -> Raiden Q (3N4 + N2C) -> Beidou E (Perfect Counter) -> Bennett E Q -> Beidou Q -> Xiangling E -> Bennett E -> Xiangling -> Raiden E -> Beidou E (PC) -> Bennett E.'''
characters = ['xiangling', 'bennett', 'raiden', 'beidou']

kqm_standard_character_configs = '''

##Character Definitions
char+=xiangling ele=pyro lvl=90 hp=10874.915 atk=225.141 def=668.871 em=96.000 cr=.05 cd=0.5 cons=4 talent=9,9,9;
weapon+=xiangling label="deathmatch" atk=454.363 cr=0.368 refine=3;
art+=xiangling label="crimson witch of flames" count=4;
stats+=xiangling label=main hp=4780 atk=311 atk%=0.466 pyro%=0.466 cd=0.622;
stats+=xiangling label=subs atk%=.0992 cr=.3972 cd=.662 em=39.64 er=.2204 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

char+=beidou ele=electro lvl=80 hp=1 atk=210 def=1 electro%=0.24 cr=.05 cd=0.5 cons=4 talent=6,9,9;
weapon+=beidou label="serpent spine" atk=509.606 cr=0.276 refine=3 param=[stacks=5];
art+=beidou label="seal of insulation" count=4;
stats+=beidou label=main hp=4780 atk=311 atk%=.466 electro%=0.466 cd=0.622;
stats+=beidou label=subs atk%=.1984 cr=.3972 cd=.662 em=39.64 er=.1102 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

char+=bennett ele=pyro lvl=80 hp=1 atk=178 def=1 er=0.267 cr=.05 cd=0.5 cons=4 talent=6,9,9;
weapon+=bennett label="blackcliff longsword" atk=564.784 cd=0.368 refine=3;
art+=bennett label="noblesse oblige" count=4;
stats+=bennett label=main hp=4780 atk=311 er=.518 pyro%=0.466 cr=0.311;
stats+=bennett label=subs atk%=.0992 cr=.0662 cd=.1324 em=39.64 er=.3857 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

char+=raiden ele=electro lvl=80 hp=1 atk=314 def=1 er=0.32 cr=.05 cd=0.5 cons=0 talent=6,9,9;
weapon+=raiden label="the catch" atk=510 er=.459 refine=5;
art+=raiden label="seal of insulation" count=4;
stats+=raiden label=main hp=4780 atk=311 atk%=0.466 electro%=0.466 cr=0.311;
stats+=raiden label=subs atk%=.2976 cr=.1986 cd=.7944 em=39.64 er=.2204 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

'''

config = '''##Default Enemy
target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;
target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

##Actions List
active+=raiden;

# HP particle simulation. Per srl:
# it adds 1 particle randomly, uniformly distributed between 200 to 300 frames after the last time an energy drops
# so in the case above, it adds on avg one particle every 250 frames in effect
# so over 90s of combat that's 90 * 60 / 250 = 21.6 on avg
energy+=every interval=200,300 amount=1;

actions+=sequence_strict target=raiden exec=attack,attack,attack,attack,dash,attack,attack,attack,attack,dash,attack,attack,attack,attack,dash,attack,attack,charge if=.status.raidenburst>0;
# actions+=sequence_strict target=raiden exec=attack,attack,attack,attack,charge,attack,attack,attack,attack,charge,attack,attack,charge if=.status.raidenburst>0;

# Additional check to reset at the start of the next rotation
actions+=skill target=raiden if=.status.raidenskill<240;

actions+=sequence_strict target=bennett exec=burst;
actions+=sequence_strict target=xiangling exec=burst if=.status.btburst>0;
actions+=sequence_strict target=xiangling exec=skill if=.status.xianglingburst>720;

# Raiden must burst after all others.
actions+=sequence_strict target=raiden exec=burst if=.status.btburst>0&&.status.beidouburst<120;

actions+=sequence_strict target=beidou exec=attack,attack,burst,attack if=.status.btburst>0;
actions+=sequence_strict target=beidou exec=skill[counter=2];
actions+=sequence_strict target=xiangling exec=skill if=.cd.xiangling.burst>120;

# Funnelling
actions+=sequence_strict target=bennett exec=attack,skill if=.status.beidouburst>240&&.energy.xiangling<70 swap=xiangling;
actions+=sequence_strict target=bennett exec=skill if=.energy.xiangling<30 swap=xiangling;
actions+=sequence_strict target=bennett exec=skill;

actions+=attack target=xiangling active=xiangling;
actions+=attack target=bennett active=bennett;
actions+=attack target=raiden active=raiden;
'''
