title = "Raiden Hyper"
author = "Tsym#2586"
recommended_rotation_length = "20.0"
recommended_minimum_er = { raidenshogun = 2.1994000000000002, kaedeharakazuha = 1.9037, bennett = 2.1707, kujousara = 1.8366 }
recommended_loadouts = { raidenshogun = 'the catch, 4 seal of insulation', kaedeharakazuha = 'iron sting, 4 viridescent venerer', bennett = 'blackclifflongsword, 4 noblesse oblige', kujousara = 'sacrificialbow, 4 seal of insulation' }
recommended_enemy_count = 2
description = '''Recommended Rotation Duration: 20.0
Recommended Minimum ER by Character: raidenshogun: 220%; kaedeharakazuha: 190%; bennett: 217%; kujousara: 184%
Rotation Built for the Following Weapon/Artifacts: raidenshogun: the catch, 4 seal of insulation; kaedeharakazuha: iron sting, 4 viridescent venerer; bennett: blackclifflongsword, 4 noblesse oblige; kujousara: sacrificialbow, 4 seal of insulation
Recommended Enemy Count: 2
Rotation: Raiden E -> Bennett Q -> Kazuha EP Q (electro VV) -> Sara Q -> Raiden Q (3 N3C + N1C) E -> Bennett E -> Sara E CA -> Loop but do not do Raiden E again'''
characters = ['raidenshogun', 'kaedeharakazuha', 'bennett', 'kujousara']
version = "0.1.0"

kqm_standard_character_configs = '''

##Character Definitions
kaedeharakazuha char lvl=90/90 cons=0 talent=6,6,6;
kaedeharakazuha add weapon="iron sting" refine=3 lvl=90/90;
kaedeharakazuha add set="viridescent venerer" count=4;
kaedeharakazuha add stats hp=4780 atk=311 er=.518 em=374;
kaedeharakazuha add stats atk%=.0992 cr=.0662 cd=.1324 em=138.74 er=.3857 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

kujousara char lvl=80/90 cons=4 talent=6,9,9;
kujousara add weapon="sacrificialbow" refine=3 lvl=90/90;
kujousara add set="seal of insulation" count=4;
kujousara add stats hp=4780 atk=311 atk%=0.466 electro%=0.466 cr=0.311;
kujousara add stats atk%=.0992 cr=.1655 cd=.662 em=39.64 er=.3306 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

bennett char lvl=80/90 cons=4 talent=6,9,9;
bennett add weapon="blackclifflongsword" refine=3 lvl=90/90;
bennett add set="noblesse oblige" count=4;
bennett add stats hp=4780 atk=311 er=.518 pyro%=0.466 cr=0.311;
bennett add stats atk%=.0992 cr=.0662 cd=.1324 em=39.64 er=.3857 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

raidenshogun char lvl=90/90 cons=0 talent=9,9,9;
raidenshogun add weapon="the catch" refine=5 lvl=90/90;
raidenshogun add set="seal of insulation" count=4;
raidenshogun add stats hp=4780 atk=311 atk%=0.466 electro%=0.466 cr=0.311;
raidenshogun add stats atk%=.2976 cr=.1986 cd=.7944 em=39.64 er=.2204 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

'''

config = '''##Default Enemy
target lvl=100 resist=.1;
target lvl=100 resist=.1;

##Actions List
active raidenshogun;

# HP particle simulation. Per srl:
# it adds 1 particle randomly, uniformly distributed between 200 to 300 frames after the last time an energy drops
# so in the case above, it adds on avg one particle every 250 frames in effect
# so over 90s of combat that's 90 * 60 / 250 = 21.6 on avg
energy every interval=200,300 amount=1;

raidenshogun attack,attack,attack,charge,attack,attack,attack,charge,attack,attack,charge,attack,charge  +if=.status.raidenburst>0;

# Need to hold at the start or otherwise Kazuha won't get an electro VV proc due to timing with Bennett Q
raidenshogun skill  +if=.status.raidenskill<360 +swap_lock=40;
# Refresh at end of burst rotation
raidenshogun skill  +if=.cd.raidenshogun.burst<600&&.status.btburst==0;

# Bennett burst goes after XQ burst for uptime alignment. Attack to proc swords
bennett burst  +if=.cd.kujousara.burst<270;

kaedeharakazuha skill,high_plunge,burst  +if=.status.btburst>0;

kujousara burst[wave_attack_procs=111]  +if=.status.btburst>0;
kujousara skill,aim  +if=.status.btburst>0&&.cd.kujousara.burst<300;

# Raiden must burst after all others. Requires an attack to allow Bennett buff to apply
raidenshogun burst  +if=.status.btburst>0;

# Gap fill until next rotation
# kaedeharakazuha skill,high_plunge; 
bennett skill  +if=.status.btburst==0;
kujousara skill,aim; 

bennett attack  +is_onfield;
kujousara attack  +is_onfield;
'''
