title = "Raiden Overvape"
author = "Tsym#2586"
recommended_rotation_length = "25.0"
recommended_minimum_er = { xiangling = 1.2204, xingqiu = 1.5306, bennett = 1.6526999999999998, raidenshogun = 2.1994000000000002 }
recommended_loadouts = { xiangling = 'deathmatch, 4 crimson witch of flames', xingqiu = 'amenoma kageuchi, 4 seal of insulation', bennett = 'blackcliff longsword, 4 noblesse oblige', raidenshogun = 'the catch, 4 seal of insulation' }
recommended_enemy_count = 1
description = '''Recommended Rotation Duration: 25.0
Recommended Minimum ER by Character: xiangling: 122%; xingqiu: 153%; bennett: 165%; raidenshogun: 220%
Rotation Built for the Following Weapon/Artifacts: xiangling: deathmatch, 4 crimson witch of flames; xingqiu: amenoma kageuchi, 4 seal of insulation; bennett: blackcliff longsword, 4 noblesse oblige; raidenshogun: the catch, 4 seal of insulation
Recommended Enemy Count: 1
Rotation: Raiden E -> Xingqiu E Q -> Bennett Q E -> Xiangling Q E -> Raiden Q (3N4 + N3C) -> Bennett E -> Xiangling -> Bennett E -> Xiangling. Attacks weaved wherever possible to proc Rainswords (~14 waves during rotation). ~10/12 Pyronado hits vaped in ST.'''
characters = ['xiangling', 'xingqiu', 'bennett', 'raidenshogun']
version = "0.1.0"

kqm_standard_character_configs = '''

##Character Definitions
xiangling char lvl=90/90 cons=4 talent=9,9,9;
xiangling add weapon="deathmatch" refine=3 lvl=90/90;
# xiangling add weapon="staff of homa" refine=1 lvl=90/90;
xiangling add set="crimson witch of flames" count=4;
xiangling add stats hp=4780 atk=311 em=187 pyro%=0.466 cd=0.622;
xiangling add stats atk%=.1984 cr=.3641 cd=.4634 em=79.28 er=.2204 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

xingqiu char lvl=80/90 cons=4 talent=6,9,9;
xingqiu add weapon="amenoma kageuchi" refine=3 lvl=90/90;
xingqiu add set="seal of insulation" count=4;
xingqiu add stats hp=4780 atk=311 atk%=0.466 hydro%=0.466 cr=0.311;
xingqiu add stats atk%=.0992 cr=.1986 cd=.5958 em=39.64 er=.3306 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

bennett char lvl=80/90 cons=4 talent=6,9,9;
bennett add weapon="blackcliff longsword" refine=3 lvl=90/90;
bennett add set="noblesse oblige" count=4;
bennett add stats hp=4780 atk=311 em=187 pyro%=0.466 cr=0.311;
bennett add stats atk%=.0992 cr=.0662 cd=.1324 em=39.64 er=.3857 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

raidenshogun char lvl=80/90 cons=0 talent=6,9,9;
raidenshogun add weapon="the catch" refine=5 lvl=90/90;
raidenshogun add set="seal of insulation" count=4;
raidenshogun add stats hp=4780 atk=311 atk%=0.466 electro%=0.466 cr=0.311;
raidenshogun add stats atk%=.2976 cr=.1986 cd=.7944 em=39.64 er=.2204 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

'''

config = '''##Default Enemy
target lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;
# target lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

##Actions List
active raidenshogun;

# HP particle simulation. Per srl:
# it adds 1 particle randomly, uniformly distributed between 200 to 300 frames after the last time an energy drops
# so in the case above, it adds on avg one particle every 250 frames in effect
# so over 90s of combat that's 90 * 60 / 250 = 21.6 on avg
energy every interval=200,300 amount=1;

raidenshogun attack,attack,attack,attack,dash,attack,attack,attack,attack,dash,attack,attack,attack,attack,dash,attack,attack,charge  +if=.status.raidenburst>0;

# Additional check to reset at the start of the next rotation
raidenshogun skill  +if=.status.xianglingburst==0&&.energy.xingqiu>70&&.energy.xiangling>70;
raidenshogun skill  +if=.status.raidenskill==0;

# Skill is required before burst to activate Kageuchi. Otherwise ER is barely not enough
# For rotations #2 and beyond, need to ensure that Guoba is ready to go. Guoba timing is about 300 frames after XQ fires his skill
xingqiu skill[orbital=1],burst[orbital=1],attack  +if=.cd.xiangling.skill<300;

# Bennett burst goes after XQ burst for uptime alignment. Attack to proc swords
bennett burst,attack,skill  +if=.status.xqburst>0&&.cd.xiangling.burst<180;

# Only ever want to XL burst in Bennett buff and after XQ burst for uptime alignment
xiangling burst,attack,skill,attack,attack  +if=.status.xqburst>0&&.status.btburst>0;
# Second set of actions needed in case Guoba CD comes off while pyronado is spinning
xiangling burst,attack  +if=.status.xqburst>0&&.status.btburst>0;
xiangling skill ;

# Raiden must burst after all others. Requires an attack to allow Bennett buff to apply
raidenshogun burst  +if=.status.xqburst>0&&.status.xianglingburst>0&&.status.btburst>0;

# Funnelling
bennett attack,skill  +if=.status.xqburst>0&&.energy.xiangling<70 +swap_to=xiangling;
bennett skill  +if=.energy.xiangling<70 +swap_to=xiangling;
bennett skill  +if=.energy.xingqiu<80 +swap_to=xingqiu;
bennett attack,skill  +if=.status.xqburst>0 +if=.energy.raidenshogun<90 +swap_to=raidenshogun;

xingqiu attack  +if=.status.xqburst>0;
xiangling attack  +is_onfield;
bennett attack  +is_onfield;
xingqiu attack  +is_onfield;
raidenshogun attack  +is_onfield;
'''
