title = "Double Pyro Raiden with Fischl"
author = "Tsym#2586"
recommended_rotation_length = "21.0"
recommended_minimum_er = { xiangling = 1.2204, raiden = 2.1994000000000002, bennett = 1.6526999999999998, fischl = 1.1102 }
recommended_loadouts = { xiangling = 'deathmatch, 4 crimson witch of flames', raiden = 'the catch, 4 seal of insulation', bennett = 'blackcliff longsword, 4 noblesse oblige', fischl = "the stringless, 2 thundering fury, 2 gladiator's finale" }
recommended_enemy_count = 1
description = '''Recommended Rotation Duration: 21.0
Recommended Minimum ER by Character: xiangling: 122%; raiden: 220%; bennett: 165%; fischl: 111%
Rotation Built for the Following Weapon/Artifacts: xiangling: deathmatch, 4 crimson witch of flames; raiden: the catch, 4 seal of insulation; bennett: blackcliff longsword, 4 noblesse oblige; fischl: the stringless, 2 thundering fury, 2 gladiator's finale
Recommended Enemy Count: 1
Rotation: Raiden E -> Bennett Q E -> Xiangling Q E -> Fischl Q -> Raiden Q (3N4 + N2C) -> Fischl E -> Bennett E -> Xiangling'''
characters = ['xiangling', 'raiden', 'bennett', 'fischl']

kqm_standard_character_configs = '''

##Character Definitions
char+=xiangling ele=pyro lvl=90 hp=10874.915 atk=225.141 def=668.871 em=96.000 cr=.05 cd=0.5 cons=4 talent=9,9,9;
weapon+=xiangling label="deathmatch" atk=454.363 cr=0.368 refine=3;
art+=xiangling label="crimson witch of flames" count=4;
stats+=xiangling label=main hp=4780 atk=311 em=187 pyro%=0.466 cd=0.622;
stats+=xiangling label=subs atk%=.1984 cr=.3641 cd=.4634 em=79.28 er=.2204 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

char+=bennett ele=pyro lvl=80 hp=1 atk=178 def=1 er=0.267 cr=.05 cd=0.5 cons=4 talent=6,9,9;
weapon+=bennett label="blackcliff longsword" atk=564.784 cd=0.368 refine=3;
art+=bennett label="noblesse oblige" count=4;
stats+=bennett label=main hp=4780 atk=311 em=187 pyro%=0.466 cr=0.311;
stats+=bennett label=subs atk%=.0992 cr=.0662 cd=.1324 em=39.64 er=.3857 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

char+=fischl ele=electro lvl=80 hp=1 atk=227 def=1 atk%=0.240 cr=.05 cd=0.5 cons=4 talent=6,9,9;
weapon+=fischl label="the stringless" atk=510 em=165 refine=3;
art+=fischl label="thundering fury" count=2;
art+=fischl label="gladiator's finale" count=2;
stats+=fischl label=main hp=4780 atk=311 atk%=0.466 electro%=0.466 cr=0.311;
stats+=fischl label=subs atk%=.1488 cr=.2317 cd=.7282 em=39.64 er=.1102 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

char+=raiden ele=electro lvl=80 hp=1 atk=314 def=1 er=0.32 cr=.05 cd=0.5 cons=0 talent=6,9,9;
weapon+=raiden label="the catch" atk=510 er=.459 refine=5;
art+=raiden label="seal of insulation" count=4;
stats+=raiden label=main hp=4780 atk=311 atk%=0.466 electro%=0.466 cr=0.311;
stats+=raiden label=subs atk%=.2976 cr=.1986 cd=.7944 em=39.64 er=.2204 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

'''

config = '''##Default Enemy
target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;
# target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

##Actions List
active+=bennett;

# HP particle simulation. Per srl:
# it adds 1 particle randomly, uniformly distributed between 200 to 300 frames after the last time an energy drops
# so in the case above, it adds on avg one particle every 250 frames in effect
# so over 90s of combat that's 90 * 60 / 250 = 21.6 on avg
energy+=every interval=200,300 amount=1;

actions+=sequence_strict target=raiden exec=attack,attack,attack,attack,attack,dash,attack,attack,attack,dash,attack,attack,attack,attack,dash,attack,attack,charge if=.status.raidenburst>300;

actions+=skill target=raiden if=.status.raidenskill<300;

actions+=sequence_strict target=bennett exec=burst,skill if=.energy.xiangling>75&&.cd.xiangling.burst<120&&.cd.xiangling.skill<240;

actions+=sequence_strict target=xiangling exec=burst,skill if=.status.btburst>0;

actions+=sequence_strict target=fischl exec=attack,attack,burst if=.status.btburst>0;
actions+=skill target=fischl if=.status.fischloz==0;

actions+=burst target=raiden if=.status.xianglingburst>0&&.status.btburst>0;

# Feeding
actions+=skill target=bennett if=.energy.xiangling<77&&.status.btburst==0 swap=xiangling;

actions+=attack target=xiangling active=xiangling;
actions+=attack target=bennett active=bennett;
actions+=attack target=fischl active=fischl;
'''
