title = "Double Pyro Raiden with Fischl"
author = "Tsym#2586"
recommended_rotation_length = "21.0"
recommended_minimum_er = { xiangling = 1.2204, raidenshogun = 2.1994000000000002, bennett = 1.6526999999999998, fischl = 1.1102 }
recommended_loadouts = { xiangling = 'deathmatch, 4 crimson witch of flames', raidenshogun = 'the catch, 4 seal of insulation', bennett = 'blackclifflongsword, 4 noblesse oblige', fischl = "the stringless, 2 thundering fury, 2 gladiator's finale" }
recommended_enemy_count = 1
description = '''Recommended Rotation Duration: 21.0
Recommended Minimum ER by Character: xiangling: 122%; raidenshogun: 220%; bennett: 165%; fischl: 111%
Rotation Built for the Following Weapon/Artifacts: xiangling: deathmatch, 4 crimson witch of flames; raidenshogun: the catch, 4 seal of insulation; bennett: blackclifflongsword, 4 noblesse oblige; fischl: the stringless, 2 thundering fury, 2 gladiator's finale
Recommended Enemy Count: 1
Rotation: Raiden E -> Bennett Q E -> Xiangling Q E -> Fischl Q -> Raiden Q (3N4 + N2C) -> Fischl E -> Bennett E -> Xiangling'''
characters = ['xiangling', 'raidenshogun', 'bennett', 'fischl']
version = "0.1.0"

kqm_standard_character_configs = '''

##Character Definitions
xiangling char lvl=90/90 cons=4 talent=9,9,9;
xiangling add weapon="deathmatch" refine=3 lvl=90/90;
xiangling add set="crimson witch of flames" count=4;
xiangling add stats hp=4780 atk=311 em=187 pyro%=0.466 cd=0.622;
xiangling add stats atk%=.1984 cr=.3641 cd=.4634 em=79.28 er=.2204 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

bennett char lvl=80/90 cons=4 talent=6,9,9;
bennett add weapon="blackclifflongsword" refine=3 lvl=90/90;
bennett add set="noblesse oblige" count=4;
bennett add stats hp=4780 atk=311 em=187 pyro%=0.466 cr=0.311;
bennett add stats atk%=.0992 cr=.0662 cd=.1324 em=39.64 er=.3857 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

fischl char lvl=80/90 cons=4 talent=6,9,9;
fischl add weapon="the stringless" refine=3 lvl=90/90;
fischl add set="thundering fury" count=2;
fischl add set="gladiator's finale" count=2;
fischl add stats hp=4780 atk=311 atk%=0.466 electro%=0.466 cr=0.311;
fischl add stats atk%=.1488 cr=.2317 cd=.7282 em=39.64 er=.1102 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

raidenshogun char lvl=80/90 cons=0 talent=6,9,9;
raidenshogun add weapon="the catch" refine=5 lvl=90/90;
raidenshogun add set="seal of insulation" count=4;
raidenshogun add stats hp=4780 atk=311 atk%=0.466 electro%=0.466 cr=0.311;
raidenshogun add stats atk%=.2976 cr=.1986 cd=.7944 em=39.64 er=.2204 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

'''

config = '''##Default Enemy
target lvl=100 resist=.1;
# target lvl=100 resist=.1;

##Actions List
active bennett;

# HP particle simulation. Per srl:
# it adds 1 particle randomly, uniformly distributed between 200 to 300 frames after the last time an energy drops
# so in the case above, it adds on avg one particle every 250 frames in effect
# so over 90s of combat that's 90 * 60 / 250 = 21.6 on avg
energy every interval=200,300 amount=1;

raidenshogun attack,attack,attack,attack,attack,dash,attack,attack,attack,dash,attack,attack,attack,attack,dash,attack,attack,charge  +if=.status.raidenburst>300;

raidenshogun skill  +if=.status.raidenskill<300;

bennett burst,skill  +if=.energy.xiangling>75&&.cd.xiangling.burst<120&&.cd.xiangling.skill<240;

xiangling burst,skill  +if=.status.btburst>0;

fischl attack,attack,burst  +if=.status.btburst>0;
fischl skill  +if=.status.fischloz==0;

raidenshogun burst  +if=.status.xianglingburst>0&&.status.btburst>0;

# Feeding
bennett skill  +if=.energy.xiangling<77&&.status.btburst==0 +swap_to=xiangling;

xiangling attack  +is_onfield;
bennett attack  +is_onfield;
fischl attack  +is_onfield;
'''
