title = "Raiden Beidou Bennett Xiangling Desync"
author = "Tsym#2586"
recommended_rotation_length = "nan"
recommended_minimum_er = { xiangling = 1.2204, bennett = 2.1707, raidenshogun = 2.1994000000000002, beidou = 1.3102 }
recommended_loadouts = { xiangling = 'deathmatch, 4 crimson witch of flames', bennett = 'blackcliff longsword, 4 noblesse oblige', raidenshogun = 'the catch, 4 seal of insulation', beidou = 'serpent spine, 4 seal of insulation' }
recommended_enemy_count = 2
description = '''Recommended Rotation Duration: nan
Recommended Minimum ER by Character: xiangling: 122%; bennett: 217%; raidenshogun: 220%; beidou: 131%
Rotation Built for the Following Weapon/Artifacts: xiangling: deathmatch, 4 crimson witch of flames; bennett: blackcliff longsword, 4 noblesse oblige; raidenshogun: the catch, 4 seal of insulation; beidou: serpent spine, 4 seal of insulation
Recommended Enemy Count: 2
Rotation: No fixed rotation and sim is run over 90 seconds. Ordering of ability usage until 20s goes something like:
Raiden E -> Bennett Q E -> Xiangling Q E -> Raiden Q (3N4 + N2C) -> Beidou E (Perfect Counter) -> Bennett E Q -> Beidou Q -> Xiangling E -> Bennett E -> Xiangling -> Raiden E -> Beidou E (PC) -> Bennett E.'''
characters = ['xiangling', 'bennett', 'raidenshogun', 'beidou']
version = "0.1.0"

kqm_standard_character_configs = '''

##Character Definitions
xiangling char lvl=90/90 cons=4 talent=9,9,9;
xiangling add weapon="deathmatch" refine=3 lvl=90/90;
xiangling add set="crimson witch of flames" count=4;
xiangling add stats hp=4780 atk=311 atk%=0.466 pyro%=0.466 cd=0.622;
xiangling add stats atk%=.0992 cr=.3972 cd=.662 em=39.64 er=.2204 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

beidou char lvl=80/90 cons=4 talent=6,9,9;
beidou add weapon="serpent spine" refine=3 lvl=90/90;
beidou add set="seal of insulation" count=4;
beidou add stats hp=4780 atk=311 atk%=.466 electro%=0.466 cd=0.622;
beidou add stats atk%=.1984 cr=.3972 cd=.662 em=39.64 er=.1102 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

bennett char lvl=80/90 cons=4 talent=6,9,9;
bennett add weapon="blackcliff longsword" refine=3 lvl=90/90;
bennett add set="noblesse oblige" count=4;
bennett add stats hp=4780 atk=311 er=.518 pyro%=0.466 cr=0.311;
bennett add stats atk%=.0992 cr=.0662 cd=.1324 em=39.64 er=.3857 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

raidenshogun char lvl=80/90 cons=0 talent=6,9,9;
raidenshogun add weapon="the catch" refine=5 lvl=90/90;
raidenshogun add set="seal of insulation" count=4;
raidenshogun add stats hp=4780 atk=311 atk%=0.466 electro%=0.466 cr=0.311;
raidenshogun add stats atk%=.2976 cr=.1986 cd=.7944 em=39.64 er=.2204 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

'''

config = '''##Default Enemy
target lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;
target lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

##Actions List
active raidenshogun;

# HP particle simulation. Per srl:
# it adds 1 particle randomly, uniformly distributed between 200 to 300 frames after the last time an energy drops
# so in the case above, it adds on avg one particle every 250 frames in effect
# so over 90s of combat that's 90 * 60 / 250 = 21.6 on avg
energy every interval=200,300 amount=1;

raidenshogun attack,attack,attack,attack,dash,attack,attack,attack,attack,dash,attack,attack,attack,attack,dash,attack,attack,charge  +if=.status.raidenburst>0;
# raidenshogun attack,attack,attack,attack,charge,attack,attack,attack,attack,charge,attack,attack,charge  +if=.status.raidenburst>0;

# Additional check to reset at the start of the next rotation
raidenshogun skill  +if=.status.raidenskill<240;

bennett burst; 
xiangling burst  +if=.status.btburst>0;
xiangling skill  +if=.status.xianglingburst>720;

# Raiden must burst after all others.
raidenshogun burst  +if=.status.btburst>0&&.status.beidouburst<120;

beidou attack,attack,burst,attack  +if=.status.btburst>0;
beidou skill[counter=2]; 
xiangling skill  +if=.cd.xiangling.burst>120;

# Funnelling
bennett attack,skill  +if=.status.beidouburst>240&&.energy.xiangling<70 +swap_to=xiangling;
bennett skill  +if=.energy.xiangling<30 +swap_to=xiangling;
bennett skill; 

xiangling attack  +is_onfield;
bennett attack  +is_onfield;
raidenshogun attack  +is_onfield;
'''
