title = "Xiao Geo Bros with Plunge Hits"
author = "Tsym#2586"
recommended_rotation_length = "21.5"
recommended_minimum_er = { sucrose = 1.1102, albedo = 1.1102, zhongli = 1.4162000000000001, xiao = 1.2204 }
recommended_loadouts = { sucrose = 'thrilling tales of dragon slayers, 4 viridescent venerer', albedo = 'harbinger of dawn, 4 noblesse oblige', zhongli = 'favonius lance, 4 noblesse oblige', xiao = "deathmatch, 2 viridescent venerer, 2 gladiator's finale" }
recommended_enemy_count = 2
description = '''Recommended Rotation Duration: 21.5
Recommended Minimum ER by Character: sucrose: 111%; albedo: 111%; zhongli: 142%; xiao: 122%
Rotation Built for the Following Weapon/Artifacts: sucrose: thrilling tales of dragon slayers, 4 viridescent venerer; albedo: harbinger of dawn, 4 noblesse oblige; zhongli: favonius lance, 4 noblesse oblige; xiao: deathmatch, 2 viridescent venerer, 2 gladiator's finale
Recommended Enemy Count: 2
Rotation: Zhongli E Hold -> Albedo E Q (omitted in rotation 2 as he doesn't regen enough energy) -> Sucrose E -> Xiao E E Q Plunge x12. Xiao plunges each also do one instance of falling plunge damage.'''
characters = ['sucrose', 'albedo', 'zhongli', 'xiao']
version = "0.1.0"

kqm_standard_character_configs = '''

##Character Definitions
zhongli char lvl=80/90 cons=0 talent=6,9,9;
zhongli add weapon="favonius lance" refine=3 lvl=90/90;
zhongli add set="noblesse oblige" count=4;
zhongli add stats hp=4780 atk=311 hp%=1 cr=0.311;
zhongli add stats atk%=.0992 cr=.2648 cd=.1324 em=39.64 er=.1102 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

albedo char lvl=80/90 cons=0 talent=6,9,9;
albedo add weapon="harbinger of dawn" refine=5 lvl=90/90;
# albedo add weapon="cinnabar spindle" refine=5 lvl=90/90;
albedo add set="noblesse oblige" count=4;
# albedo add set="husk of opulent dreams" count=4;
albedo add stats hp=4780 atk=311 def%=.518 geo%=0.466 cr=0.311;
albedo add stats atk%=.0992 cr=.331 cd=.7944 em=39.64 er=.1102 hp%=.0992 hp=507.88 atk=33.08 def%=.248 def=39.36;

xiao char lvl=90/90 cons=0 talent=9,9,9;
xiao add weapon="deathmatch" refine=3 lvl=90/90;
xiao add set="viridescent venerer" count=2;
xiao add set="gladiator's finale" count=2;
xiao add stats hp=4780 atk=311 atk%=0.466 anemo%=0.466 cd=0.622;
xiao add stats atk%=0.0992 cr=.3972 cd=.662 em=39.64 er=.2204 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

sucrose char lvl=90/90 cons=4 talent=8,8,10;
sucrose add weapon="thrilling tales of dragon slayers" refine=5 lvl=90/90;
sucrose add set="viridescent venerer" count=4;
sucrose add stats hp=4780 atk=311 em=561;
sucrose add stats atk%=.0992 cr=.0662 cd=.1324 em=138.74 er=.1102 hp%=.0992 hp=507.88 atk=33.08 def%=.124 def=39.36;

'''

config = '''##Default Enemy
target lvl=100 resist=.1;
target lvl=100 resist=.1;

##Actions List
active zhongli;

# HP particle simulation. Per srl:
# it adds 1 particle randomly, uniformly distributed between 200 to 300 frames after the last time an energy drops
# so in the case above, it adds on avg one particle every 250 frames in effect
# so over 90s of combat that's 90 * 60 / 250 = 21.6 on avg
# From elijam assumptions: https://discord.com/channels/763583452762734592/851428030094114847/884832120650993805
energy every interval=200,300 amount=1;

xiao high_plunge[plunge_hits=1]  +if=.status.xiaoburst>60;

zhongli skill[hold_nostele=1] +limit=1;
zhongli skill[hold_nostele=1] +if=.cd.xiao.burst<500;
albedo skill,burst  +if=.cd.xiao.burst<300;
albedo skill,attack  +if=.cd.xiao.burst<300;

sucrose skill,skill +swap_to=xiao +if=.cd.xiao.burst==0&&.energy.xiao<60&&.tags.sucrose.eCharge>1;
sucrose skill +swap_to=xiao +if=.cd.xiao.burst==0;

xiao skill,skill,burst; 

# Funneling
sucrose skill +swap_to=xiao +if=.cd.xiao.burst==0;

xiao attack  +swap_lock=100;
zhongli attack  +is_onfield;
'''
