#title, author and description are mandatory fields
title = "4TF Bennett"
author = "srl"
description = "This is a non optimized test configuration for 4TF Bennett. Should only be used as a starting point for fine tuning. Teams revolves around Bennett using the 4 TF set and triggering as many overloads as possible to reduce Bennett E cd to 1sec"
tags = [
    "bennett",
    "xingqiu",
    "beidou",
    "fischl",
    "4tf",
    "thundering fury",
    "overload"
]
# version is an optional field for authors to keep track
version = "0.1.0"
# characters should be array of character names (all lowercase); this is mandatory
characters = ["bennett", "xingqiu", "beidou", "fischl"]
# config is the action list, stored in multiline string
config = '''
target lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;
active xingqiu;

xingqiu skill,burst  +swap_lock=100;
xingqiu skill  +if=.status.xingqiu.energy<80 +swap_lock=100;
xingqiu burst ;
bennett burst ;
beidou skill,burst  +swap_lock=100;
beidou burst ;
fischl burst  +if=.status.fischloz==0;
fischl skill  +if=.status.fischloz==0;
beidou skill  +swap_lock=600;
bennett skill,attack; 
fischl attack  +is_onfield;
beidou attack  +is_onfield;
xingqiu attack  +is_onfield;
bennett attack  +is_onfield;
'''
