#title, author and description are mandatory fields
title = "Simple Yoimiya vape"
author = "srl"
description = "This is a non optimized test configuration for Yoimiya + Xingqiu comp. Should only be used as a starting point for fine tuning."
tags = ["yoimiya", "xingqiu", "bennett", "sucrose", "vape"]
# version is an optional field for authors to keep track
version = "0.1.0"
# characters should be array of character names (all lowercase); this is mandatory
characters = ["yoimiya", "xingqiu", "bennett", "sucrose"]
# config is the action list, stored in multiline string
config = '''
target lvl=100 resist=.1;
active bennett;

yoimiya attack  +if=.status.yoimiyaskill>0;
yoimiya burst  +is_onfield;
sucrose skill  +if=.debuff.res.t1.vvpyro==0;
bennett burst ;
xingqiu skill,burst  +swap_lock=100;
xingqiu skill  +if=.energy.xingqiu<80 +swap_lock=100;
xingqiu burst ;
yoimiya skill ;
yoimiya burst ;
yoimiya attack  +is_onfield;
xingqiu attack  +is_onfield;
bennett attack  +is_onfield;
'''
